#!/bin/bash

# exit when command fails
set -e

# Keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG

# Echo a message before exiting
trap 'echo "\"${last_command}\" command completed with exit code $?."' EXIT

# Verify format and execute tests
./gradlew verGJF --daemon
./gradlew test --daemon
